### ISSUE TITLE
config file - better explanation of variables

### ISSUE THREAD

**Issue by JacekKac** [crazystick/dynamic-cloud-dns-client#5]
```
# the Cloud DNS zone to update
DCDNS_ZONE=**_MYHOST_**
```
https://console.cloud.google.com/net-services/dns/zones/**_MYHOST_**/details?project=myexampleproject 

is it a proper mapping?

# the DNS hostname to update, e.g. your.host.com
DCDNS_HOST=dynamichost.domain.com

https://console.cloud.google.com/net-services/dns/zones/**_MYHOST_**/rrsets/your.host.com./A/view?project=myexampleproject 

is it a proper mapping?

# the URL of your deployed cloud function
DCDNS_FUNCTION_URL=https://us-central1-myexampleproject .cloudfunctions.net/updateHost
cant figure  out where to find "**us-central1**" i have got 
https://console.cloud.google.com/compute/instances?project=myexampleproject => Zone = "**northamerica-northeast2-a**" is it the same ?

**Comment by crazystick** [comment]
This project is a client for [Dynamic Cloud DNS](https://github.com/srueg/dynamic-cloud-dns) - the README over there explains how to deploy the cloud function. Once you have it deployed, you'll have a URL for the cloud function like your other examples:

https://console.cloud.google.com/functions/details/europe-west1/updateHost?env=gen1&project=myexampleproject

`europe-west1` is your region and `updateHost` the name of your cloud function.

The other two variables `DCDNS_ZONE` and `DCDNS_HOST` you have correct.
